language: generic
sudo: required
services:
  - docker
  #travis undeestand this as we can now use docker cli commands - create copy of docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-883526769685"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCEY_KEY
  secret_acces_key:
    secure: "$AWS_SECRET_KEY"
